### PR TITLE
Updated network_connection_duration and vendor_event_category

### PR DESCRIPTION
**Pull request by bud1979**
## Notes for Reviewers

- [ ] The commit history must be preserved - please use the rebase-merge or standard merge option instead of squash-merge
- [ ] Sync up with the author before merging

### CODE REVIEW

**Comment by miwent** [comment]
shouldn't network_connection_duration be expressed as a long or time field, something that could be used for filtering (showing long sessions by searching network_connection_duration>{a value) or calculations (sum of network_connection duration for X)?

**Comment by bud1979** [comment]
I would think so, but would need some help in understanding how to convert a field like 00:02:43 to a field like that. I am all good moving there if you could help me with that :)

**Comment by miwent** [comment]
Will storing this field as a millisecond field work? That would work for this specific instance using the code snippet:
```
    let epoch = parse_date("1970-01-01T00:00:00.000Z", "yyyy-MM-dd'T'HH:mm:ss.SSSZ");
    let test_ts = parse_date (
        value: "00:01:32",
        pattern: "HH:mm:ss"
    );
    set_field("_test_interval", test_ts - epoch );
```

But we may be dealing with other fields represented with other values in the future.  We don't have to solve those today, but we should be aware of the possibilities.  I think it would be fine, would you agree @bud1979 ?

**Comment by bud1979** [comment]
I agree there, I think milliseconds is a good estimate for now.

**Review by miwent — APPROVED** [review]

**Pull request merged**
